#!/bin/sh
if test ! $(id -u) == 0
then
 sudo $0 "$@"
 exit $?
fi

killall rtm-t-stream-disk 2>/dev/null
#            --fan speed--- set  zone val%  100% : 17500 rpm
ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x40 >/dev/null && echo fan normal || echo fan failed
