#!/bin/bash
if test $(id -u) -ne 0
then
 sudo $0 "$@"
 exit $?
fi



if   [ -z $1 ]
then
 kill `pidof rtm-t-stream-disk` 2>/dev/null
 rm -rf /data/*
else
 for DEVICEID in ${1//,/ }
 do
 PIDFILE=/dev/rtm-t.$DEVICEID.ctrl/streamer_pid
 if   [ -f $PIDFILE ]
 then
  pid=$(cat $PIDFILE)
  if [ $pid -gt 0 ]
  then
   kill $pid 2>/dev/null
   to=0
   while [ 0$(cat $PIDFILE) -eq $pid -a $to -lt 10 ]
   do sleep .1;let to=$to+1
   done
   if [ 0$(cat $PIDFILE) -eq $pid ]
   then echo failed to kill $PIDFILE = $pid
   fi
  fi
 fi
 rm -rf /data/$DEVICEID
 done
fi
