#!/bin/bash
if [ -z $UUT ]
then
 echo "UUT env undefined: e.g. define UUT=192.168.0.100"
 exit 1
fi
echo UUT=$UUT
if ( uname -v | grep Debian )
then NC="nc -q 1"
else NC="nc"
fi
if [ -z $1 ]
then ports=0
else ports="${1/,/ }"
fi
echo ports = $ports
for uut in $UUT
do
# A: 1, B: 0
# max 500MB/line i.e. 25 a 10MHz
if [ ! -z $2 ]
then $NC $uut 4233 <<< "aggregator sites=$2" # A
fi
if [ ! -z $3 ]
then $NC $uut 4232 <<< "aggregator sites=$3" # B
fi
$NC $uut 4220 << EOF >/dev/null&
SIG:ZCLK_SRC         INT33M
SYS:CLK:FPMUX        ZCLK
SYS:CLK:Si5326:PLAN 10M
SYS:CLK:DIST_CLK_SRC 1
SYS:CLK:OE_CLK1_ZYNQ 1
SYS:CLK:OE_CLK1_ELF* 1
SIG:SRC:CLK:1        MCLK
STREAM_OPTS          --null-copy
OVERSAMPLING         0
TRANSIENT:SOFT_TRIGGER 0
TRANSIENT 1
EOF
done
echo master
sleep 1
for uut in $UUT
do
if [ "$($NC $uut 4221 <<< module_name|head -c 6)" = "acq425" ]
then CLKDIV="CLKDIV 10"
fi
$NC $uut 4221 << EOF >/dev/null&
$CLKDIV
clk      1,1,1
trg      1,1,1
event0   0,0,0
event1   0,0,0
EOF
done
echo slave
wait %
echo done
/mgt/mgt-arm $ports
trap "/mgt/mgt-deinit $ports" EXIT
for port in $ports
do /mgt/mgt-stream $port&
done
for uut in $UUT
do echo `$NC $uut 4220 <<< "streamtonowhered start"`
done
echo streamtonowhered start
sleep 12
for port in $ports
do cat /dev/rtm-t.$port.ctrl/streamer_pid
done
for uut in $UUT
do echo `$NC $uut 4220 <<< "soft_trigger 1"`
done
echo soft_trigger
sleep 1
for uut in $UUT
do echo `$NC $uut 4220 <<< "streamtonowhered stop"`
done
echo streamtonowhered stop
tree /data | tail -n 10
df -h /data
for port in $ports
do head -c 64 /data/$port/000001/$port.00|hexdump
done
