#!/bin/bash
if [ $(id -u) -ne 0 ]
then
 sudo $0 "$@"
 exit $?
fi

if [ -z $1 ]
then DEVS=0,1
else DEVS=$1
fi

if !(grep -q afhba /proc/modules>/dev/null 2>&1)
then
  module=/mgt/afhba.ko
  insmod "$module" ll_mode_only=0 reg_access_verbose=0 \
    afhba4_stream=2 afhba_nports=2 nbuffers=99 buffer_len=0x400000 \
    aurora_monitor=-1 eot_interrupt=0 WORK_TO=1 \
    dma_descriptor_ram=1 assume_stuck_buffers_are_ok=1 \
    && echo "$module" > /var/log/afhba.log
  sleep 1
fi

for DEV in ${DEVS//,/ }
do
  if !(grep +LANE_UP /dev/rtm-t.$DEV.ctrl/aurora>/dev/null 2>&1)
  then
    echo lanes are down
    exit 1
  fi
  /mgt/mgt-deinit $DEV
done
